### ISSUE TITLE
Consentscope relation to Patient Will code

### ISSUE THREAD

**Issue by JensPenny** [hl7-be/patientwill#11]
I'm posting this after validation with a colleague within Nexuzhealth.

We get the cardinalities for the fields consent.provision.code(0..*) and consent.scope (1..1). We have a practical question though. 
Our system requires a consent.provision.code. We are assuming that we can derive a consent.scope from these patient will codes. Are we correct in this assumption? 

For quick reference: 
* [here is the patient will code value set](https://hl7belgium.org/profiles/ehealth/be-core/1.2.2/ValueSet-be-vs-patientwill-code.html)
* [here is the consent scope value set](http://hl7.org/fhir/R4/valueset-consent-scope.html)

**Comment by bdc-ehealth** [comment]
WG: we will make the will.code in the logical model, which corresponds to the consent.provision.code in the FHIR resource mandatory. We will enquire for the difference between scope and category in the FHIR resource. So more investigation needed.

**Comment by bdc-ehealth** [comment]
@JensPenny 
WG: Jens, you must be looking at an old version of the profile. The current version can be found here: https://build.fhir.org/ig/hl7-be/patientwill/branches/issue-1

**Comment by bdc-ehealth** [comment]
Proposal @Alexis-MDS : we propose to remove MS, and add the fact that we will not use it as a business rule.

WG: @annenerenhausen will check with the business experts if this is necessary.
